function mssim = ssim(rband,fband,row,column,band)
msoriginal= multibandread(rband, [row column band], ...
                    'uint16', 0, 'bsq', 'ieee-le', ...
                    {'Band', 'Range', [1 band]} );
   


msfusa = multibandread(fband, [row column band], ...
                    'uint16', 0, 'bsq', 'ieee-le', ...
                    {'Band', 'Range', [1 band]} );

 [mssim,ssim_map]=ssimf(msoriginal,msfusa);         